class case():
    def __init__(self, caseid, activetrial, completetrial, penaltypending, defendant, accuser, accusationtime, trialendtime, record, deferredpenalty = 0, penaltyid = "-1", judge = None, witnessqty = 0):
        self.caseid = caseid #unique id for the case
        self.activetrial = activetrial #boolean: true if case has made it to trial (starttrial by judge)
        self.completetrial = completetrial #boolean: true if trial has completed (forgiven, judged innocent, or penalty executed)
        self.penaltypending = penaltypending #boolean: true if judged guilty and penalty handed off to accuser, but accuser hasn't executed penalty yet.
        self.defendant = defendant #user who is being accused of a crime
        self.accuser = accuser #user who is accusing someone of a crime (the prosecution)
        self.accusationtime = accusationtime #the date/time when the accusation was filed
        self.trialendtime = trialendtime #the date/time when the trial ended
        self.record = record #a list of tuples, one for each message which was added to the record for this trial.
        self.deferredpenalty = deferredpenalty #boolean: true if the accuser has been given the right to execute penalty
        self.penaltyid = penaltyid
        self.judge = judge #user with judge role who has agreed to preside over the case
        self.witnessqty = witnessqty

accusationdroptime = 1440 #if an accusation is made, the accusation will be erased unless 'witness' is called against it at least twice in this many minutes
trialrecordtime = 7200 #trials will remain on the record this many minutes after they have been marked as complete.

judicialpenalties = [(0, "acquit", "The defendant is counted innocent. No penalty."), #Penalty 0 is referenced outside the penalty function, so it shouldn't be changed.
                     (1, "nickchange", "Changes their nick to something silly. Accepts custom name as argument."),
                     (2, "chastize", "Sends message to the defendant, saying \"What you did was wrong. Don't do it again.\""),
                     (3, "lutherchastize", "Hits them with a mean quote from Martin Luther."),
                     (4, "minutemute", "Mutes the defendant for 5 minutes"),
                     (5, "hourmute", "Mutes the defendant for an hour"),
                     (6, "kick", "Kicks the defendant"),
                     (7, "dayban", "Bans the defendant for 24 hours"),
                     (8, "permaban", "Bans the defendant forever")
                     ]

penaltyList = ["Acquit", "Nick-Change", "Chastize", "Luther Chastize", "Minute Mute", "Hour Mute", "Kick", "Day Ban", "Permaban"]

namecombodb1 = ["Fat","Buddy","Sticky","Old","Texas","Hollerin","Ugly","Green","Happy","Honey","Curly","Pretty","Jailhouse","PegLeg","Rambunctious","Sleepy","Bald","Skinny","Blind","Big","Yella","Toothless","Screamin","Biggy","Washboard","Steely"]
namecombodb2 = ["Bones","Money","Harp","Legs","Eyes","Lemon","Killer","Hips","Lips","Fingers","Boy","Liver","Gumbo","Foot","Mama","Back","Duke","Dog","Boy","Baby","Chicken","Pickles","Sugar","Willy","Tooth","Smoke"]
namecombodb3 = ["Jackson","McGee","Hopkins","Dupree","McGreen","Brown","Jones","Rivers","Malone","Washington","Smith","Parker","Lee","Thompkins","Gooober","Bradley","Hawkins","Jefferson","Davis","Franklin","White","Jenkins","Baily","Johnson","Blue","Allison"]


lutherinsults = { "The Small Catechism from The Book of Concord, p.348" : "You live like simple cattle or irrational pigs and, despite the fact that the gospel has returned, have mastered the fine art of misusing all your freedom.",
            "The Large Catechism from The Book of Concord, p.379" : "You shameful gluttons and servants of your bellies are better suited to be swineherds and keepers of dogs.",
            "The Large Catechism from The Book of Concord, p.381" : "You deserve not only to be given no food to eat, but also to have the dogs set upon you and to be pelted with horse manure.",
            "The Large Catechism from The Book of Concord, p.382" : "Oh, what mad senseless fools you are!",
            "The Large Catechism from The Book of Concord, p.409" : "For this you deserve to have God deprive you of his Word and blessing and once again allow preachers of lies to arise who lead you to the devil - and wring sweat and blood out of you besides.",
            "The Large Catechism from The Book of Concord, p.413" : "All your holiness is only stench and filth, and it merits nothing but wrath and damnation.",
            "The Large Catechism from The Book of Concord, p.418" : "May your grain spoil in the barn, your beer in the cellar, your cattle perish in the stall. Yes, your entire hoard ought to be consumed by rust so that you will never enjoy it.",
            "The Large Catechism from The Book of Concord, p.422" : "You relish and delight in the chance to stir up someone else's dirt like pigs that roll in manure and root around in it with their snouts.",
            "Heidelberg Disputation from Vol. 31 of Luther's Works, p.51" : "Your sin smells to high heaven.",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.87" : "Your words are so foolishly and ignorantly composed that I cannot believe you understand them.",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.88" : "You are the most insane heretics and ingrafters of heretical perversity.",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.154" : "What you say is a blasphemy that has made you worthy of a thousand deaths.",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.164" : "Behold, indeed, this little golden work of a golden teacher! It is a work most worthy of golden letters, and lest there be something about it which is not golden, it must be handed down by golden disciples, namely, by those about whom it is said, \"The idols of the nations are silver and gold. They have eyes, but they see not.\"",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.175" : "You are worthy only to be mocked by the words of error.",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.183" : "It is presumptuous for people who are as ignorant as you are not to take up the work of a herdsman.",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.184" : "What bilgewater of heresies has ever been spoken so heretically as what you have said?",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.184" : "What do you mean when you say this? Are you dreaming in the throes of a fever or are you laboring under a madness?",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.184" : "Your astute minds have been completely turned into stinking mushrooms.",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.185" : "You are the prostitute of heretics!",
            "Explanations of the Ninety-Five Theses from Vol. 31 of Luther's Works, p.204" : "I am tired of the pestilent voice of your sirens.",
            "Proceedings at Augsburg from Vol. 31 of Luther's Works, p.289" : "You are a bungling magpie, croaking loudly.",
            "Proceedings at Augsburg from Vol. 31 of Luther's Works, p.290" : "You forgot to purge yourself with hellabore while you were preparing to fabricate this lie.",
            "The Freedom of a Christian from Vol. 31 of Luther's Works, p.336" : "You are more corrupt than any Babylon or Sodom ever was, and, as far as I can see, are characterized by a completely depraved, hopeless, and notorious godlessness.",
            "The Freedom of a Christian from Vol. 31 of Luther's Works, p.336" : "Your home, once the holiest of all, has become the most licentious den of thieves, the most shameless of all brothels, the kingdom of sin, death, and hell. It is so bad that even Antichrist himself, if he should come, could think of nothing to add to its wickedness.",
            "Why the Books of Pope Were Burned from Vol. 31 of Luther's Works, p.386" : "What devilish unchristian thing would you not undertake?",
            "Why the Books of Pope Were Burned from Vol. 31 of Luther's Works, p.392" : "You are an extraordinary creature, being neither God nor man. Perhaps you are the devil himself.",
            "Why the Books of Pope Were Burned from Vol. 31 of Luther's Works, p.393" : "Even if the Antichrist appears, what greater evil can he do than what you have done and do daily?",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.30" : "It may be that you want to build yourself a heaven of your own, like those jugglers build themselves out of linen cloth at the Shrove Tuesday carnival. Is it not disgusting that we have to hear such foolish and childish things from you?",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.38" : "In our country, fruit grows on trees and from trees, and meditation upon sin grows from contrition. But in your land, trees may grow on fruits, contrition from sins, people walk on their ears, and everything is upside down.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.39" : "O you wolf in Christendom!",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.41" : "You know less than does a log on the ground.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.46" : "I think that all the devils have at once entered into you.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.46" : "You are worse than all the devils. What you have done, no devil has ever done. Your end is near, you son of perdition and Antichrist! Stop now, you are going to far!",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.47" : "You are the true, chief, and final Antichrist.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.48" : "How far will you go, O devilish pride?",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.52" : "All Christians should be on guard against your antichristian poison.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.56" : "I think you received these ideas in your pipe dreams.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.61" : "You are in all you do the very opposite of Christ as befits a true Antichrist.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.63" : "You are a person of sin and the child of perdition, leading all the world with you to the devil, using your lying and deceitful ways.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.64" : "You are not a pious fraud, but an infernal, diabolical, antichristian fraud.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.64" : "You are the Roman Nimrod and a teacher of sin.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.66" : "It is the old dragon from the abyss of hell who is standing before me!",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.78" : "You hold fast to human dreams and the doctrines of devils.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.80" : "If you who are assembled in a council are so frivolous and irresponsible as to waste time and money on unnecessary questions, when it is the business of a council to deal only with the important and necessary matters, we should not only refuse to obey you, but consider you insane or criminals.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.81" : "Even Lucifer was not guilty of so great a sacrilege in heaven, for he only presumed to be God's equal. God help us!",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.82" : "You condemned the holy gospel and replaced it with the teaching of the dragon from hell.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.83" : "Your words are un-Christian, antichristian, and spoken by the inspiration of the evil spirit.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.83" : "What happened to the house built on sand in Matthew 7 will also happen to you.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.85" : "Must we believe your nightmares?",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.85" : "Look how this great heretic speaks brazenly and sacrilegiously.",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.87" : "You run against God with the horns of your pride up in the air and thus plunge into the abyss of hell. Woe unto you, Antichrist!",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.89" : "You are the devil's most dangerous tool!",
            "Defense and Explanation of All the Articles from Vol. 32 of Luther's Works, p.99" : "It seems I must have liars and villains for opponents. I am not worthy in the sight of God that a godly and honorable person should discuss these matters with me in a Christian way. This is my greatest lament.",
            "Against Latomus from Vol. 32 of Luther's Works, p.138" : "May the Lord Jesus protect me and all devout souls from your contagion and your company!",
            "Against Latomus from Vol. 32 of Luther's Works, p.140" : "This venom - the mere smell of which kills a man!",
            "Against Latomus from Vol. 32 of Luther's Works, p.140" : "You are a Baal-zebub - that is, a man of flies.",
            "Against Latomus from Vol. 32 of Luther's Works, p.140" : "You are full of poisonous refuse and insane foolishness.",
            "Against Latomus from Vol. 32 of Luther's Works, p.142" : "You are ignorant, stupid, godless blasphemers.",
            "Against Latomus from Vol. 32 of Luther's Works, p.142" : "You moderate enforcer and eulogizer of moderation. You are one of those bloody and deceitful people who affect modesty in words and appearance, but who meanwhile breathe out threats and blood.",
            "Against Latomus from Vol. 32 of Luther's Works, p.143" : "We leave you to your own devices, for nothing properly suits you except hypocrisy, flattery, and lies.",
            "Against Latomus from Vol. 32 of Luther's Works, p.145" : "In lying fashion you ignore what even children know.",
            "Against Latomus from Vol. 32 of Luther's Works, p.145" : "The reward of such flattery is what your crass stupidity deserves. Therefore, we shall turn from you, a sevenfold stupid and blasphemous wise person.",
            "Against Latomus from Vol. 32 of Luther's Works, p.146" : "People of your sort are hirelings, dumb dogs unable to bark, who see the wolf coming and flee or, rather, join up with the wolf.",
            "Against Latomus from Vol. 32 of Luther's Works, p.146" : "You are a wolf and apostle of Satan.",
            "Against Latomus from Vol. 32 of Luther's Works, p.147" : "You are the ultimate scourges of the world, the Antichrist together with your sophists and bishops.",
            "Against Latomus from Vol. 32 of Luther's Works, p.147" : "You cowardly slave, you corrupt sycophant, with your sickening advice!",
            "Against Latomus from Vol. 32 of Luther's Works, p.148" : "You are idiots and swine.",
            "Against Latomus from Vol. 32 of Luther's Works, p.150" : "Every letter of yours breathes Moabitish pride. So much can a single bull inflate a single bubble that you practically make distinguished asses into gods.",
            "Against Latomus from Vol. 32 of Luther's Works, p.150" : "You sophistic worms, grasshoppers, locusts, frogs and lice!",
            "Against Latomus from Vol. 32 of Luther's Works, p.152" : "You completely close your mind and do nothing but shout, \"Anathema, anathema, anathema!\" so that by your own voice you are judged mad.",
            "Against Latomus from Vol. 32 of Luther's Works, p.153" : "Let this generation of vipers prepare itself for unquenchable fire!",
            "Against Latomus from Vol. 32 of Luther's Works, p.159" : "You rush forward as an ass under the pelt of a lion.",
            "Against Latomus from Vol. 32 of Luther's Works, p.160" : "In appearance and words you simulate modesty, but you are so swollen with haughtiness, arrogance, pride, malice, villainy, rashness, superciliousness, ignorance, and stupidity that there is nothing to surpass you.",
            "Against Latomus from Vol. 32 of Luther's Works, p.176" : "Blind moles!",
            "Against Latomus from Vol. 32 of Luther's Works, p.205" : "We despise your whorish impudence.",
            "Against Latomus from Vol. 32 of Luther's Works, p.205" : "You arsonists, enemies of languages and truth!",
            "Against Latomus from Vol. 32 of Luther's Works, p.219" : "Before God and men I accuse all of you as arsonists, blasphemers, murderers, and ravagers of Christian piety.",
            "Against Latomus from Vol. 32 of Luther's Works, p.223" : "My soul, like Ezekiel's, is nauseated at eating your bread covered with human dung. Do you know what this means?",
            "Against Latomus from Vol. 32 of Luther's Works, p.223" : "You pant after the garlic and melons of Egypt and have already long suffered from perverted tastes.",
            "Against Latomus from Vol. 32 of Luther's Works, p.242" : "You people are more stupid than a block of wood.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.22" : "You foster in your heart a Lucian, or some other pig from Epicurus' sty.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.29" : "You reek of nothing but Lucian, and you breathe out on me the vast drunken folly of Epicurus.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.36" : "You find things irreverent, inquisitive, and vain just as all ungodly men do, or rather, as the demons and the damned find things hateful and detestable.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.76" : "You seem to be wrangling about goat's wool, like the man who watched the play in an empty theater.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.77" : "You are dumber than Seriphian frogs and fishes.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.113" : "You conduct yourself like one drunk or asleep, belching out between your snores, \"Yes, No.\"",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.127" : "How is it, then, that you drivel like people in their second childhood?",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.144" : "Just as in a picture or dream you might see the king of the flies with his lances of straw and shields of hay arrayed against a real and regular army of seasoned human troops, that is how you go to war.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.224" : "Proteus is no Proteus compared with you.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.236" : "You do nothing with all your profusion of words but fight a fire with dry straw.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.244" : "Perhaps you want me to die of unrelieved boredom while you keep on talking.",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.254" : "Are you ignorant of what it means to be ignorant?",
            "The Bondage of the Will from Vol. 33 of Luther's Works, p.268" : "You speak and act only as an ungodly person does.",
            "Concerning the Ministry from Vol. 40 of Luther's Works, p.17" : "I would not smell the foul odor of your name.",
            "Concerning the Ministry from Vol. 40 of Luther's Works, p.25" : "Are you not making an elephant out of a fly? What wonder workers!",
            "Concerning the Ministry from Vol. 40 of Luther's Works, p.30" : "You worship a Dagon and a god of your stomachs.",
            "Concerning the Ministry from Vol. 40 of Luther's Works, p.34" : "You have a priesthood of Satan.",
            "Concerning the Ministry from Vol. 40 of Luther's Works, p.34" : "As for the signs of your peculiar priesthood, we are willing to let you boast of these mean things, for we know it would be quite easy to shave, anoint, and clothe in a long robe even a pig or a block of wood.",
            "Letter to the Princes of Saxony from Vol. 40 of Luther's Works, p.52" : "In your hiding place you use the most fearless language as though you were full of three holy spirits. Such unseemly boasting reveals clearly what kind of a spirit you are.",
            "Letter to the Christians at Strassburg from Vol. 40 of Luther's Works, p.67" : "Truly, I never imagined, and at the same time was shocked, to see how deeply you still cling to your errors.",
            "Letter to the Christians at Strassburg from Vol. 40 of Luther's Works, p.67" : "You are a coarse devil who hurts me but little.",
            "Letter to the Christians at Strassburg from Vol. 40 of Luther's Works, p.68" : "Such loose, lame, empty talk, set forth on the basis of your own reason and idiosyncrasy, would lead me to believe first of all that your opinions amount to nothing.",
            "Letter to the Christians at Strassburg from Vol. 40 of Luther's Works, p.69" : "Get out in the name of a thousand devils, and break your neck before you are out of the city.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.82" : "You have a perverted spirit that thinks only of murdering the conscience.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.89" : "You teach the disorderly masses to break into this field in disorder like pigs.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.96" : "Phooey on you, you servant of idols!",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.110" : "You are a toad eater and a fawner.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.111" : "Take care, you evil and wrathful spirits. God may ordain that in swallowing you may choke to death.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.118" : "Perhaps you like to hear yourself talk, as the stork its own clattering.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.131" : "You are the cousins of the Antichrist.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.141" : "You are the sin-master and soul-murdered.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.146" : "Just as the devil is disorderly and jumbles things together, so your writings and head are equally disordered and mixed up, so that it is exceedingly annoying to read and difficult to remember what you write.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.147" : "Do you not see here the devil, the enemy of God's order?",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.147" : "Who ever does not know the devil might be misled by these many splendid words to think that five holy spirits were in possession of you. Whoever differs from you is a papist twice over who crucifies or murders Christ; indeed, those who differ from you are Scribes. Whoever agrees with you, however, is up to their boots in the spirit and is a learned light. O wonderful saints! What do you think of yourselves? Do you fully grasp what kind of a spirit you have?",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.148" : "You plunge in like a sow to devour pearls, and like a dog tearing holy things to pieces.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.149" : "In devil's fashion you go out where God would enter and enter where God goes out. It ought surprise no one that I call you a devil.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.150" : "Listen, murdered of souls and sinful spirit!",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.150" : "Stupid spirit.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.151" : "What light can there be in heads that hold such tangible darkness?",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.155" : "We may confidently suppose and be sure that your spirit will produce evidence and proof when the devil becomes God.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.157" : "The devil rides you.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.161" : "You have fought against us as one would attack a cliff with a broken straw.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.164" : "You have lost head, eyes, brain, and heart, since you know neither shame nor fear, and dare wager all according to your whims.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.167" : "If I were to repay you in slanderous words for the way you have blasphemed so maliciously and terribly, where would I find enough words? For your sins and blasphemy are immeasurable.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.185" : "I beg you put your glasses on your nose, or blow your nose a bit, to make your head lighter and the brain clearer.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.185" : "You do nothing more than latch on to a small word and smear over with your spittle as you please, but meanwhile you do not take into account other texts which overthrow you who smear and spits, so that you are up-ended with all four limbs in the air.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.186" : "You are like the ostrich, the foolish bird which thinks it is wholly concealed when it gets its neck under a branch. Or like small children, who hold their hands in front of their eyes and seeing nobody imagine that no one sees them either. In general, you are so stupid that it makes one feel like vomiting.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.189" : "The silly, feeble devil thinks no one sees it. No, my fellow, we see you well enough. You haven't used enough make-up; you need more and other colors.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.193" : "This is pure knavery with which the devil here deals. Tell me, you who are so pure, why are you here so filthy?",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.194" : "You ought to feel shame in your hearts, you great gruff asses' heads.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.200" : "What a fine spirit we have here, who would drive out the devil by a devil. Indeed you would disgrace public truth with public lies.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.202" : "Finally you cannot help yourself but spew out good, fat, strong lies, and like a mad person speak against yourself.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.205" : "Were you against the heathen Priapus, he would probably pass wind in the face of such well-aimed terror.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.205" : "How this spirit makes a food of itself in all its words. You can say nothing but that it boomerangs on your own head and hits you so that you not only are blackened but are made to stagger as a drunkard.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.209" : "See how your spirit here walks on eggs, how you twist and turn, how you talk as if you had mush in your mouth and mumble like a half-dead, despairing person.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.211" : "You like as an arch rascal and disgraceful scoundrel.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.216" : "You act and speak as a bride of the devil, expressing what the devil inspires. All blasphemous words of this kind are nothing but childish, mad, sacrilegious ideas, and lies which are not worthy of answer.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.216" : "You poor devil.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.217" : "You have surrendered yourself and dared to become an avowed enemy of God, wanting to race rather than trot to hell.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.218" : "Wither now, dear factious spirits? I will let you write and shriek for a thousand years and need not oppose you with more than one word. O how one word smashes you prophets and spirits into one lump in the gutter.",
            "Against the Heavenly Prophets from Vol. 40 of Luther's Works, p.222" : "You boast of possessing the Spirit, more than the apostles, and yet for years now have secretly prowled about and flung around your dung. Were you a true spirit you would at once have come forward and given proof of you call by signs and words. But you are a treacherous, secret devil who sneaks around in corners until you have done your damage and spread your poison.",
            "Concerning Rebaptism from Vol. 40 of Luther's Works, p.252" : "There you are, like butter in sunshine.",
            "Concerning Rebaptism from Vol. 40 of Luther's Works, p.259" : "As far as I have been able to see and hear, you have no argument but high-sounding words of sacrilege. Everyone ought properly to shun and avoid you as messengers of none other than the devil.",
            "Instructions for the Visitors of Parish Pastors from Vol. 40 of Luther's Works, p.271" : "You are spiritual scarecrows and monk calves.",
            "Instructions for the Visitors of Parish Pastors from Vol. 40 of Luther's Works, p.271" : "What good purpose can you lazy, sluggish bullies accomplish?",
            "Instructions for the Visitors of Parish Pastors from Vol. 40 of Luther's Works, p.272" : "You are poisonous, worthless gossips.",
            "Instructions for the Visitors of Parish Pastors from Vol. 40 of Luther's Works, p.273" : "You are undisciplined heads who out of utter perversity are able to do nothing in common or in agreement, but are different and self-centered in heart and life.",
            "Instructions for the Visitors of Parish Pastors from Vol. 40 of Luther's Works, p.310" : "You are like a herd of swine being invited to the table of a prince. You understand not such an honor, but only ravage what is set before you, even soiling the prince.",
            "The Keys from Vol. 40 of Luther's Works, p.326" : "If you had looked with slumbering and only half-open eyes, the clear bright light would have struck you so that you would have had to open your eyes wide and awaken. But now since you did not do that, but only listened as if in a dream, you speak like a sleepy toper when one asks him whether he would not like to go home and he replies, \"Bring me another,\" and really believes that one brings him another drink.",
            "The Keys from Vol. 40 of Luther's Works, p.326" : "What else can one say here, except that these ideas originate in your own wanton concoctions, or in a drunken dream?",
            "The Keys from Vol. 40 of Luther's Works, p.344" : "You gamble with God's Word like a rogue.",
            "The Keys from Vol. 40 of Luther's Works, p.344" : "Heaven and earth are in danger of caving in because of your heresies.",
            "The Keys from Vol. 40 of Luther's Works, p.345" : "You are indeed cheated and deceived by falsehood, and that is what all like you deserve.",
            "The Keys from Vol. 40 of Luther's Works, p.351" : "You are not human beings, but empty shells and shadows.",
            "The Keys from Vol. 40 of Luther's Works, p.352" : "You dear asses.",
            "The Keys from Vol. 40 of Luther's Works, p.360" : "You are jugglers of imaginary sins.",
            "The Keys from Vol. 40 of Luther's Works, p.362" : "Even if your writings were from an angel from heaven I would take this horrible document, and, after having used it as toilet paper, wipe its nose.",
            "The Keys from Vol. 40 of Luther's Works, p.363" : "You are like swine who indiscriminately devour everything.",
            "Infiltrating and Clandestine Preachers from Vol. 40 of Luther's Works, p.383" : "You are emissaries of the devil.",
            "Infiltrating and Clandestine Preachers from Vol. 40 of Luther's Works, p.384" : "You are the true print and touch of the devil.",
            "Infiltrating and Clandestine Preachers from Vol. 40 of Luther's Works, p.388" : "What pig sties could compare in goings-on with you?",
            "Infiltrating and Clandestine Preachers from Vol. 40 of Luther's Works, p.393" : "Whoever tolerates and listens to you should know that they are listening to the devil himself, incarnate and abominable, as he speaks out of the mouth of a possessed person.",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.54" : "You are admirable, fine, pious sows and asses.",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.56" : "You are like mouse-dropping in the pepper.",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.72" : "Listen, you ass, you are a particularly crass ass, indeed, you are a filthy sow!",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.124" : "You are the white devil and a glittering Satan.",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.132" : "You are pious and honest people, who cannot do anything but calumniate and lie.",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.150" : "Snot-nose!",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.158" : "You should rightly be called lawyers for asses.",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.159" : "Are you not mad, and crazy, and crass Nestorians, not knowing when you say yes and when you say no, stating one thing in the premise and another in the conclusion? Away with you stupid asses and fools!",
            "On the Councils and the Church from Vol. 41 of Luther's Works, p.160" : "You are a brothel-keeper and the devil's daughter in hell.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.185" : "You have set out to rub your scabby, scurvy head against honor.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.185" : "You curse, blaspheme, skriek, struggle, bellow, and spit, so that, if people really heard you utter words, they would gather with chains and bars, just as if you were possessed by a legion of devils and had to be seized and bound.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.185" : "It makes me tingle with pleasure from head to toe when I see that through me, poor wretched man that I am, God the Lord maddens and exasperates you hellish and worldly people, so that in your spite you will burst and tear yourselves to pieces - while I sit under the shade of faith and the Lord's Prayer, laughing at you devils and your crew and you blubber and struggler in your great fury.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.185" : "You blubber and writhe along with all the devils in hell.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.186" : "I had not supposed or expected your arrogant spirit to seek such a ridiculous and childish reason for lying; you should have better reasons.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.187" : "Since you are such vulgar blockheads that you think such lewd and stupid gossip will harm me or bring you honor, you are the real Hanswursts - blockheads, boors, and dunderheads.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.187" : "Think what you will, so make in your pants, hang it round your neck, then make a jelly of it and eat it like the vulgar sows and asses you are!",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.188" : "I would sit still and blithely watch how you, the devil, and your sausages and your tripes vainly fret and torment yourselves, and blubber and writhe, achieving nothing except to make us laugh and make you own case worse. Indeed, I would like to see you say aloud what you write, for if you did, people would gather with chains and bars and out of sympathy would seize and bind you as demoniacs. And if people did not do this, then, perhaps at God's prompting, oxen and swine would trample you to death with their horns and hoofs.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.190" : "You are the devil's donkey.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.202" : "This new thing you have devised is the vilest cesspool that the devil has on earth.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.202" : "May the devil stay with you in this blasphemous, murderous, sinful, pernicious thing.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.205" : "You sharp-eyed bats.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.211" : "You live like Epicureans and sows. So the fat is in the fire!",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.211" : "You no longer have, as you did several centuries ago, a cunning devil spurring you on, but a palpable blockhead, a crude devil, who in his malice can no longer disguise himself.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.212" : "You vulgar boor, blockhead, and lout, you ass to cap all asses, screaming your heehaws.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.219" : "For you are an excellent person, as skilful, clever, and versed in Holy Scripture as a cow in a walnut tree or a sow on a harp.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.221" : "A seven-year-old child, indeed, a silly fool, can figure it out on his fingers - although you, stupid ass, cannot understand anything.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.225" : "You, devil and Hanswurst, are in this matter a particularly silly wurst to lie so shamefully.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.231" : "You have the master-devil all right.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.235" : "Doctor Sow.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.238" : "God has punished you by making you incapable of understanding truth, virtue, or honor, thus handing you over to the devil to tell nothing but lies, indeed, to do all that is evil, and to upset all that is good.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.239" : "For you know that everybody realized how you treat your worthy spouse - not only like an utterly mad brute and drunkard, but also like a senseless raving tyrant, who daily and hourly gorges and fills himself up, not with wine, but with the devil, like Judas at the Last Supper. Out of your whole body, in all you do and are, you simply spew out the devil, with blaspheming, cursing, lying, committing adultery, raving, flaying, murdering, setting fires, etc, so that one cannot find your like in history.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.242" : "You poisonous loudmouth.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.242" : "You stink like devilish filth flung into Germany.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.244" : "I think that if you were alone in the field, an angry cat would be enough to scare you away.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.244" : "Is not what I said before true, that you have eaten and drunk yourself full of devils, and so spew vainglorious devils out of your hellish gorge?",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.245" : "You wear a pair of cobweb trousers, like a man who, being naked, put on a new to hide his shame.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.249" : "You arch-assassin and bloodhound, the like of which has never been seen under the sun.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.249" : "There you are in the chains of divine judgment, bound in hell like all the devils.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.250" : "You pusillanimous scoundrel.",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.250" : "You should not write a book before you have heard an old sow fart; and then you should open your jaws with awe, saying, \"Thank you, lovely nightingale, that is just the text for me!\"",
            "Against Hanswurst from Vol. 41 of Luther's Works, p.255" : "I think that you would not be bold enough to blow at a farmer's fence if you knew that there was a flail behind the door; you would lift your heels in quite a manly way, as though it were snowing flails behind you.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.263" : "You abominable abomination.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.264" : "Your Hellishness.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.264" : "You are like a magician who conjures gulden into the mouths of silly people, but when they open their mouths they have horse dirt in them.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.264" : "The very devil himself would thank you for such an event, and no one but the miserable devil and his devilish scum would go there.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.270" : "You are the scum of all the scoundrels.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.272" : "You are an abominable arch-heretic.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.277" : "You are desperate, thorough arch-rascals, murderers, traitors, liars, the very scum of all the most evil people on earth. You are full of all the worst devils in hell - full, full, and so full that you can do nothing but vomit, throw, and blow out devils!",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.279" : "You are blasphemous, abominable rascals and damned scum of Satan.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.280" : "If you are furious, you can do something in your pants and hang it around your necks - that would be a musk apple and pacem for such gentle saints.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.280" : "Gently, dear Pauli, dear donkey, don't dance around! Oh, dearest little ass, don't dance around - dearest, dearest little donkey, don't do it. For the ice is very solidly frozen this year because there was no wind - you might fall and break a leg. If a fart should escape you while you were falling, the whole world would laugh at you and say, \"Ugh, the devil! How the ass has befouled himself!\" And that would be a great crime. Oh, that would be dangerous! So consider your own great danger beforehand, Hellish One.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.281" : "You say, \"What comes out of our mouth must be kept!\" I hear it - which mouth do you mean? The one from which the farts come? (You can keep that yourself!)",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.281" : "You are a crude ass, and an ass you will remain!",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.285" : "Everyone can see that such a sentence must have been blown into you by all the existing devils with one breath.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.288" : "You are the founder and master of all sins.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.288" : "Even if we were stones and wooden blocks, we could see by your works throughout all the world that you are lost, desperate children of the devil and also mad, crude asses in Scripture. Someone probably would like to curse you so that you might be struck down by lightning and thunder, burned by hellish fire, have the plague, syphilis, epilepsy, the plague of St. Anthony, leprosy, carbuncles, and all the plagues - but these are all caresses, and God has long ago punished you with greater plagues, just like God's despisers and blasphemers should be punished.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.290" : "The hellish Satan drives you.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.296" : "You roar as one possessed and full of devils.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.298" : "Yes, what happened to you is what must happen when one paints the devil above the door and asks him to be godfather.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.300" : "Dear God, what an utterly shameless, blasphemous lying-mouth you are!",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.300" : "You think like this, \"As I am a crude ass, and do not read the books, so there is no one in the world who reads them; rather, when I let my braying heehaw, heehaw resound, or even let out a donkey's fart, then everyone will have to consider it pure truth.\"",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.309" : "You are such outrageous, shameless blockheads.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.310" : "You are a little pious prancer.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.329" : "You hellish scum.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.330" : "You loathsome, accursed, atrocious monster.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.332" : "I must stop: I can no longer rummage in your blasphemous, hellish devil's filth and stench.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.334" : "But what do you say? \"Come here, Satan! And if you had more worlds than this, I would accept them all , and not only worship you, but also lick your behind.\"",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.334" : "All you say is sealed with the devil's own dirt.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.335" : "Why would anyone tolerate such things from someone like you, a rotten paunch, crude ass and fart-ass?",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.341" : "You are the worst rascal of all the rascals on earth!",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.344" : "I can with good conscience consider you a fart-ass and an enemy of God.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.344" : "I was frightened and thought I was dreaming, it was such a thunderclap, such a great horrid fart did you let go here! You certainly pressed with great might to let out such a thunderous fart - it is a wonder that it did not tear your hole and belly apart!",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.349" : "May God punish you, I say, you shameless, barefaced liar, devil's mouthpiece, who dares to spit out, before God, before all the angels, before the dear sun, before all the world, your devil's filth.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.350" : "You ass, abecedarian, and bacchanal.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.357" : "You are the head of all the worst scoundrels on earth, a vicar of the devil, an enemy of God, an adversary of Christ, a destroyer of Christ's churches; a teacher of lies, blasphemies, and idolatries; an arch-thief and robber; a murderer of kings and inciter to all kinds of bloodshed; a brothel-keeper over all brothel-keepers and all vermin, even that which cannot be named; an Antichrist, a person of sin and child of perdition; a true werewolf.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.360" : "You are inimical asses!",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.360" : "A natural donkey, which carries sacks to the mill and eats thistles, can judge you - indeed, all creatures can! For a donkey knows it is a donkey and not a cow. A stone knows it is a stone; water is water, and so on through all the creatures. But you mad asses do not know you are asses.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.363" : "I would not dream of judging or punishing you, except to say that you were born from the behind of the devil, are full of devils, lies, blasphemy, and idolatry; are the instigator of these things, God's enemy, Antichrist, desolater of Christendom, and steward of Sodom.",
            "Against the Roman Papacy, an Institution of the Devil from Vol. 41 of Luther's Works, p.376" : "Here now, you ass, with your long donkey ears and accursed liar's mouth!",
            "The Estate of Marriage from Vol. 45 of Luther's Works, p.41" : "With all your cleverness you are nothing but devil's fools.",
            "Admonition to Peace from Vol. 46 of Luther's Works, p.19" : "You, however, keep on asking for trouble and want to be hit over the head.",
            "Admonition to Peace from Vol. 46 of Luther's Works, p.33" : "Bloodthirsty prophets of murder and spirits of rebellion!",
            "Admonition to Peace from Vol. 46 of Luther's Works, p.34" : "By God's permission you might accomplish something as the heathen and blasphemers you are - and we pray that he will prevent that - but it will only be to your temporal and eternal destruction.",
            "Admonition to Peace from Vol. 46 of Luther's Works, p.35" : "You are a prophet of discord.",
            "Admonition to Peace from Vol. 46 of Luther's Works, p.42" : "Why do you insist on filling the land with blood and robbery, widows and orphans? Oh, the devil has wicked plans!",
            "Against the Robbing and Murdering Hordes of Peasants from Vol. 46 of Luther's Works, p.49" : "You are raging like mad dogs.",
            "Against the Robbing and Murdering Hordes of Peasants from Vol. 46 of Luther's Works, p.51" : "You honor and serve the devil, thus deserving death in body and soul ten times over. I have never heard of a more hideous sin.",
            "Against the Robbing and Murdering Hordes of Peasants from Vol. 46 of Luther's Works, p.51" : "Fine Christians you are! I think there is not a devil left in hell; they have all gone into you. Your raving has gone beyond measure.",
            "Against the Robbing and Murdering Hordes of Peasants from Vol. 46 of Luther's Works, p.55" : "I beg everyone who can to flee from you as from the devil himself.",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.63" : "The devil must speak through you.",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.64" : "You - like the spider which sucks only poison from the rose - draw only vain pride from the doctrine of humility.",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.64" : "You have, in fact, not a spark of knowledge, and yet you babble on and on.",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.64" : "Your hearts are so full of wicked wiles that you desire nothing more than to be offended.",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.65" : "I suspect that you are undertaking a vain and impossible task; for who can stop the mouth of a fool? Your heart is crammed so full of nonsense and \"out of the abundance of the heart, the mouth speaks.\"",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.67" : "We see you, you black, ugly devil!",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.74" : "You are a bloodhound, and a rebellious murderer and destroyer of the country.",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.84" : "I leave you to the guidance of your master, the devil, who is indeed leading you.",
            "An Open Letter on the Harsh Book Against the Peasants from Vol. 46 of Luther's Works, p.84" : "Why should I write for scoundrels and hogs like you?",
            "Whether Soldiers, too, can be Saved from Vol. 46 of Luther's Works, p.101" : "The excrement of the eagle can boast that it comes from the eagle's body even though it stinks and is useless; and so you can also be of the nobility. You people are and remain people, that is, swine and senseless beasts.",
            "Whether Soldiers, too, can be Saved from Vol. 46 of Luther's Works, p.109" : "You shall have about as much success as a dog has when he tries to bite through steel.",
            "Whether Soldiers, too, can be Saved from Vol. 46 of Luther's Works, p.112" : "You are like the frogs of old who could not put up with a log for lord; instead they got a stork that pecked their heads and devoured them. You are a desperate, accursed thing.",
            "Whether Soldiers, too, can be Saved from Vol. 46 of Luther's Works, p.122" : "You are such a coward that you try to catch every word and evaluate it like a man who tries to trap the wind in his coat.",
            "On War Against the Turk from Vol. 46 of Luther's Works, p.161" : "You are half-devil and half-man.",
            "On War Against the Turk from Vol. 46 of Luther's Works, p.175" : "We must pray against you as against other enemies of our salvation and of all good, indeed, as we pray against the devil himself.",
            "On War Against the Turk from Vol. 46 of Luther's Works, p.193" : "You are the army of the devil.",
            "On War Against the Turk from Vol. 46 of Luther's Works, p.198" : "Sodom and Gommorah, which God overwhelmed in days of old with fire and brimstone, must seem a mere jest and prelude compared with your abominations.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.217" : "You seem to me to be a real masterpiece of the devil's art.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.228" : "Shame, shame, and shame again upon your blind and despicable ingratitude.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.228" : "You are like the cawing of jackdaws and ravens, though not as good. For the daws at least like to caw; they do so gladly. But you take no pleasure in your croaking; you caw reluctantly, like the hoopoes and owls.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.229" : "See what a pious hypocrite and unproductive weed you are.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.230" : "You will not be tainted by little drops of sin, but inundated by whole cloudbursts of it. Then you will have to say that you are justly condemned to the abyss of hell as one of the most odious and vile people who ever lived.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.241" : "You're a gross, ungrateful clod, worthy of being numbered among the beasts.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.241" : "You are like hogs wallowing forever with their noses in the dunghill.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.251" : "You are the Carthusians and monks of Mammon.",
            "A Sermon on Keeping Children in School from Vol. 46 of Luther's Works, p.254" : "You are such an accursed, ungrateful wretch that you will not give a child into training for the maintenance of the gifts of God. You have everything, all of it free of charge; yet you show not a particle of gratitude. Instead you let God's kingdom and the salvation of people's souls go to ruin; you even help to destroy them. Ought not God to be angry over this? Ought not famine to come? Ought not pestilence, flu, and syphilis find us out? Ought not blind, fierce, and savage tyrants come to power? Ought not war and contention arise? Ought not evil regimes appear in our lands? Ought not our enemies plunder us? Indeed, it would not be surprising if God were to open the doors and windows of hell and pelt and shower us with nothing but devils, or let brimstone and hell-fire rain down from heaven and inundate us one and all in the abyss of hell, like Sodom and Gomorrah.",
            "On Marriage Matters from Vol. 46 of Luther's Works, p.287" : "Go, you whore, go to the devil for all I care.",
            "On Marriage Matters from Vol. 46 of Luther's Works, p.302" : "We should roundly denounce you, the devil's messengers, as rascals, villains, poisonous evil worms. Or, even if you were good friends of ours, we should denounce you as mad fools and stupid persons.",
            "On Marriage Matters from Vol. 46 of Luther's Works, p.302" : "You stinkmouths.",
            "On Marriage Matters from Vol. 46 of Luther's Works, p.319" : "You are the biggest fool on earth."
            }
